[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"
  NEXT_DISABLE_NETLIFY_FORM_DETECTION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/standalone/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
