[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_RUNTIME = "edge"
  NODE_VERSION = "18"

[build.processing]
  skip_processing = true

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
